version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: billsplit-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: billsplit123
      MONGO_INITDB_DATABASE: billsplit
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - billsplit-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: billsplit-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --requirepass billsplit123
    volumes:
      - redis_data:/data
    networks:
      - billsplit-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: billsplit-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGODB_URI: mongodb://admin:billsplit123@mongodb:27017/billsplit?authSource=admin
      REDIS_URL: redis://:billsplit123@redis:6379
      JWT_SECRET: your-super-secret-jwt-key
      JWT_EXPIRE: 30d
      CORS_ORIGIN: http://localhost:3000
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
      - redis
    networks:
      - billsplit-network
    command: npm run dev

  # Frontend Web App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: billsplit-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:5000/api
      VITE_SOCKET_URL: http://localhost:5000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - billsplit-network
    command: npm run dev

  # MinIO (S3-compatible storage for development)
  minio:
    image: minio/minio:latest
    container_name: billsplit-minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - minio_data:/data
    networks:
      - billsplit-network
    command: server /data --console-address ":9001"

  # Mailhog (Email testing)
  mailhog:
    image: mailhog/mailhog:latest
    container_name: billsplit-mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - billsplit-network

networks:
  billsplit-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data:
  minio_data:
