name: billsplit_ai
description: Smart expense sharing mobile app with AI-powered receipt scanning
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  
  # State Management
  flutter_riverpod: ^2.5.0
  riverpod_annotation: ^2.3.4
  
  # Navigation
  go_router: ^13.2.0
  
  # Networking
  dio: ^5.4.1
  retrofit: ^4.1.0
  pretty_dio_logger: ^1.3.1
  
  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  
  # Authentication
  flutter_secure_storage: ^9.0.0
  local_auth: ^2.1.8
  
  # Image & Camera
  image_picker: ^1.0.7
  camera: ^0.10.5+9
  permission_handler: ^11.3.0
  
  # OCR & AI
  google_mlkit_text_recognition: ^0.11.0
  flutter_tesseract_ocr: ^0.4.23
  
  # QR Code
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  
  # Notifications
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.19
  flutter_local_notifications: ^17.0.0
  
  # Utilities
  intl: ^0.18.1
  uuid: ^4.3.3
  collection: ^1.18.0
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  
  # UI Components
  flutter_slidable: ^3.0.1
  pull_to_refresh: ^2.0.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  lottie: ^3.0.0
  
  # Forms
  flutter_form_builder: ^9.2.1
  form_builder_validators: ^9.1.0
  
  # Charts
  fl_chart: ^0.66.2
  
  # Payment
  flutter_stripe: ^10.0.0
  
  # Analytics
  firebase_analytics: ^10.8.9
  sentry_flutter: ^7.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  freezed: ^2.4.7
  retrofit_generator: ^8.1.0
  riverpod_generator: ^2.3.11
  
  # Linting
  flutter_lints: ^3.0.1
  
  # Testing
  mockito: ^5.4.4
  bloc_test: ^9.1.6
  
  # Dev Tools
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#6366F1"
  adaptive_icon_foreground: "assets/icons/app_icon_adaptive.png"

flutter_native_splash:
  color: "#6366F1"
  image: assets/images/splash_logo.png
  android: true
  ios: true
